name: Buscript
main: buscript.BuscriptPlugin
version: maven-version-number
author: dumptruckman
softdepend: [Vault]
api-version: 1.13

commands:
  run:
    description: Runs the given script file with an optional target
    usage: /<command> <script> [player]
    permission: buscript.run
  breload:
    description: Forces any cached scripts to be reloaded (useful for registered events)
    usage: /<command>
    permission: buscript.reload

permissions:
  buscript.run:
    default: OP
  buscript.reload:
    default: OP
